networks:
  dev:
    driver: bridge 

services:
  nacmvc:
    image: munhei/nac_service:2.2.0
    container_name: nac_service
    ports:
      - 5000:5000
    networks:
      - dev
    restart: always
    depends_on:
      nac_db:
        condition: service_healthy

  nac_db:
    image: postgres:14-alpine
    container_name: nac_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NacP@ssw0rd
      - POSTGRES_DB=NacDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "su -c pg_isready postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  customer_data:
