[nac_servers]
#nordalbi02
nordalbi03

[nac_servers:vars]
ansible_user=nordalbi
# Sudo password for system update privilege escalation
#ansible_become_password=Zeltstadt

# common configuration
nac_image_tag=2.2.1
aspnetcore_environment=Production

db_name=NacDB
db_user=postgres
db_password=NacP@ssw0rd
