[nac_servers]
nordalbi02 db_role=primary
nordalbi03 db_role=standby

[nac_servers:vars]
ansible_user=nordalbi
# Sudo password for system update privilege escalation
#ansible_become_password=Zeltstadt

# common configuration
nac_image_tag=3.0.0_rc1
aspnetcore_environment=Production

db_name=NacDB
db_user=postgres
db_password=NacP@ssw0rd

db_repl_user=replicator
db_repl_password=YourReplPassword123
primary_host_ip=192.168.1.10
